### ISSUE TITLE
Void function error: evil-disable-insert-bindings

### ISSUE THREAD

**Issue by tecosaur** [Somelauw/evil-markdown#1]
Hello,

I've been using your extension with Doom Emacs and in a recent update, my use of Emacs Anywhere was broken. Doing a bit of debugging the error seems to be `Symbol’s function definition is void: evil-disable-insert-state-bindings`, and tracking that down lead me to this extension.

https://github.com/Somelauw/evil-markdown/blob/46cd81b37991c4325fc24015a610f832b0ff995d/evil-markdown.el#L213-L214

It seems that `evil-disable-insert-state-bindings` is now a `defcustom` variable, with the description "Whether insert state bindings should be used."

If it would it be possible to update this package to fix this, that would be much appriciated :crossed_fingers:

**Comment by Somelauw** [comment]
PR welcome.

**Comment by Somelauw** [comment]
Solved and pushed to master

**Comment by tecosaur** [comment]
Thanks for getting around to fixing this :)
